# Generated by Django 4.1 on 2024-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapp",
            name="industry",
            field=models.CharField(
                choices=[
                    ("tech", "Technology"),
                    ("finance", "Finance"),
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("manufacturing", "Manufacturing"),
                    ("retail", "Retail"),
                    ("hospitality", "Hospitality"),
                    ("government", "Government"),
                    ("nonprofit", "Non-Profit"),
                ],
                default=2,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobapp",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                    ("executive", "Executive"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jobapp",
            name="salary_range",
            field=models.CharField(
                choices=[
                    ("<30000", "Less than $30,000"),
                    ("30000-50000", "$30,000 - $50,000"),
                    ("50001-70000", "$50,001 - $70,000"),
                    ("70001-90000", "$70,001 - $90,000"),
                    ("90001-110000", "$90,001 - $110,000"),
                    ("110001-130000", "$110,001 - $130,000"),
                    ("130001-150000", "$130,001 - $150,000"),
                    (">150000", "More than $150,000"),
                ],
                max_length=20,
            ),
        ),
    ]
