# Generated by Django 4.1 on 2024-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_app_tracker",
            "0002_jobapp_industry_alter_jobapp_experience_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapp",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("under_review", "Under Review"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interviewed", "Interviewed"),
                    ("offer_received", "Offer Received"),
                    ("offer_accepted", "Accepted Offer"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("no_response", "No Response"),
                    ("awaiting_decision", "Awaiting Decision"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
