# Generated by Django 4.1 on 2024-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app_tracker", "0004_jobapp_file_alter_jobapp_salary_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapp",
            name="cover_letter",
            field=models.FileField(blank=True, null=True, upload_to="cover_letters/"),
        ),
        migrations.AddField(
            model_name="jobapp",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="jobapp",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
