# Generated by Django 4.1 on 2024-01-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app_tracker", "0005_jobapp_cover_letter_jobapp_resume_alter_jobapp_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapp",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
