# Generated by Django 4.1 on 2024-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_app_tracker", "0006_jobapp_employment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapp",
            name="salary_range",
            field=models.CharField(max_length=200),
        ),
    ]
